### ISSUE TITLE
Question about cage-based deformation

### ISSUE THREAD

**Issue by Cinomi** [ShiQiu0419/3D-Geometry#1]
I read codes in main.cpp for cage-based deformation and I am curious about the cage meshes used, such as cage 1 cage 4. I am in trouble in cage construction in this project. Do you mind telling me that did you use the prepared cage mesh directly or create them by yourself? If you used the prepared mesh, do you mind showing 

`    // Load a mesh in OFF format
    std::string meshPath1 = "../scans/bunny.off";
    std::string meshPath2 = "../scans/decimated-arm.off";
    std::string cage1 = "../scans/arm-cage.off";
    std::string cage2 = "../scans/arm-deformed-cage.off";
    std::string cage3 = "../scans/arm-deformed-cage2.off";
    std::string cage4 = "../scans/arm-deformed-cage3.off";
`

**Comment by ShiQiu0419** [comment]
Before deformation, I construted conresponding cage mesh manually following a simple approach:

First is to simplify the target mesh using MeshLab. Then
“Filters->Remeshing, Simplification and Reconstruction->Simplification: Quadric
Edge Collapse Decimation”. Do simplification until the model still has the basic
shape but with fewer faces. Then import the simplified mesh into Blender, modify the
cage to fit the model better. Besides, we can transform the cage to make deformed
cages for deformation.
